//Basic Spring Boot Application Structure Code Example
    // THis is generated by Initializr, showing the main class

// com.cargoship.cargoapi.CargoApiApplication.java
package com.cargoship.cargoapi;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class CargoApiApplication {

    public static void main(String[] args) {
        SpringApplication.run(CargoApiApplication.class, args);
    }

}
